#### 1.

In [ ]:
import numpy as np

# Original list
my_list = [12.23, 13.32, 100, 36.32]


# Function that creates 1D array from a list given as parameter
def array_creator(any_list):

    # Convert to 1D NumPy array
    my_arr = np.array(any_list)

    # Print the result
    print(my_arr)


# Sample use of the function
array_creator(my_list)



#### 2.

In [ ]:
import numpy as np

# Creating a new array with arange() from 2 to 10 inclusive.
new_arr = np.arange(2, 11)

# Reshaping the new arr with reshape method
new_arr = new_arr.reshape(3, 3)

# Printing the result
print(new_arr)

#### 3.

In [ ]:
import numpy as np

# Numpy array consisting of 10 zeroes
z_arr = np.zeros(10)

# Updating the 6th element to 11
z_arr[6] = 11

# Printing the result
print(z_arr)

#### 4.

In [ ]:
import numpy as np

# Creating an array with 'arange()' function that starts with 12 and ends with 37
arr1 = np.arange(12, 38)

# Print the created array
print(arr1)

#### 5.

In [ ]:
import numpy as np

# Given sample array
sample_arr = np.array([1, 2, 3, 4])

# Converting the data type of the elements of sample array to float
float_arr = sample_arr.astype('float')


# Printing the result
print(float_arr)


#### 6.

In [ ]:
import numpy as np

# Given sample array of Centigrade degrees
C_arr = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0. ])

# Converting the Centigrade degree tinto Fahrenheit degrees
F_arr = np.round(((C_arr * 9/5) + 32), 2)


# Given sample array of Fahrenheit degrees
F_new_arr = np.array([-0, 12,  45.21, 34, 99.91, 32])


# Converting the Fahrenheit degrees into Centigrade degrees
C_new_arr = np.round(((F_new_arr - 32) * 5/9), 2)


print(f"Centigrade degrees: {C_arr} \nFahrenheit degrees: {F_arr}")
print(f"Fahrenheit degrees: {F_new_arr} \nCentigrade degrees: {C_new_arr}")



#### 7.

In [ ]:
import numpy as np

# Given array
arr = np.array([10, 20, 30])

# Second array to append to arr
arr1 = np.array([40, 50, 60, 70, 80, 90])

# Result array after concatenating two arrays
arr2 = np.concatenate((arr, arr1))

print(arr2)

#### 8.

In [ ]:
import numpy as np
from numpy import random

# Creating the random array with random module from numpy
rand_arr = random.randint(100, size=10) 

# Mean() method returns the mean value of the array
mean_val = np.mean(rand_arr)

# Median() method returns the median value of the array
median_val = np.median(rand_arr)

# std() method returns the standard deviation of the array
std_val = np.std(rand_arr)

print(f"The mean: {mean_val}; \nThe median: {median_val}; \nThe standar deviation: {std_val}")

#### 9.

In [ ]:
import numpy as np
from numpy import random

# Creating the random array of the size 10x10
ten_ten = random.randint(100, size=(10, 10))

# Max() method returns the maximum value from the array
max_val = ten_ten.max()


# Min() method returns the minimum value from the array
min_val = ten_ten.min()

print(f"The maximum value: {max_val} \nThe minimum value: {min_val}")

#### 10.

In [ ]:
import numpy as np
from numpy import random

# Creating the random array of 3x3x3 and rounding it up to 2
cube = np.round(random.rand(3, 3, 3), 2)

print(cube)

[[[0.75 0.72 0.51]
  [0.63 0.55 0.25]
  [0.3  0.18 0.63]]

 [[0.9  0.78 0.13]
  [0.79 0.11 0.67]
  [0.18 0.92 0.77]]

 [[0.49 0.26 0.26]
  [0.03 0.66 0.57]
  [0.79 0.44 0.91]]]
